[tool.poetry]
name = "api-gateway"
version = "0.0.1"
description = "api-gateway for esclient"
package-mode = false
authors = ["esclient"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ariadne = "^0.26.2"
uvicorn = "^0.35.0"
grpcio-tools = "^1.73.1"

[tool.poetry.scripts]
run-server = "commentservice.server:serve"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
