# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rating.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rating.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crating.proto\x12\x06rating\"A\n\x0eRateModRequest\x12\x0e\n\x06mod_id\x18\x01 \x01(\x03\x12\x11\n\tauthor_id\x18\x02 \x01(\x03\x12\x0c\n\x04rate\x18\x03 \x01(\x05\"\"\n\x0fRateModResponse\x12\x0f\n\x07rate_id\x18\x01 \x01(\x03\"!\n\x0fGetRatesRequest\x12\x0e\n\x06mod_id\x18\x01 \x01(\x03\"H\n\x10GetRatesResponse\x12\x13\n\x0brates_total\x18\x01 \x01(\x03\x12\r\n\x05likes\x18\x02 \x01(\x03\x12\x10\n\x08\x64islikes\x18\x03 \x01(\x03\x32\x8a\x01\n\rRatingService\x12:\n\x07RateMod\x12\x16.rating.RateModRequest\x1a\x17.rating.RateModResponse\x12=\n\x08GetRates\x12\x17.rating.GetRatesRequest\x1a\x18.rating.GetRatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rating_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATEMODREQUEST']._serialized_start=24
  _globals['_RATEMODREQUEST']._serialized_end=89
  _globals['_RATEMODRESPONSE']._serialized_start=91
  _globals['_RATEMODRESPONSE']._serialized_end=125
  _globals['_GETRATESREQUEST']._serialized_start=127
  _globals['_GETRATESREQUEST']._serialized_end=160
  _globals['_GETRATESRESPONSE']._serialized_start=162
  _globals['_GETRATESRESPONSE']._serialized_end=234
  _globals['_RATINGSERVICE']._serialized_start=237
  _globals['_RATINGSERVICE']._serialized_end=375
# @@protoc_insertion_point(module_scope)
