name: "lint api-gateway"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-api-gateway:
    uses: esclient/tools/.github/workflows/lint-api-gateway-python.yml@v1.0.0
    with:
      python-version: '3.13.7'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
